[project]
name = "agenv"
version = "0.1.0"
description = "Python+Bun Environment for Agents"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.sources]
bird-feeder = { workspace = true }

[tool.uv.workspace]
members = ["libraries/*"]
